module.exports = [
  'mgcrea.ngStrap'
  'template/rating/rating.html'
  'ui.bootstrap.rating'
  'satellizer'
  'angular-loading-bar'
  'ngFileUpload'
  'permission'
  'angularUtils.directives.dirPagination'
  'elif'
  'ui.select'
  'ngMessages'
  'ui.router'
  'ngAnimate'
  'ngSanitize'
  'angular-jwt'
  require('../navbar/navbar').name
  require('../home/home').name
  require('../login/login').name
  require('../signup/signup').name
  require('../auth/auth').name
  require('../profile/profile').name
  require('../api/api').name
  require('../movie/movie').name
  require('../session/session').name
  require('../person/person').name
  require('../cinema/cinema').name
  require('../cinemas/cinemas').name
  require('../admin/admin.index/admin').name
]
